[2023-12-13 06:39:59,315: ERROR/MainProcess] Received unregistered task of type 'app.api.hou_api.render_thumb'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/636f0ab4-43df-43d7-825d-95b55ef8efd0.hiplc", "/obj/test", "72c73f65-7004-4194-8350-dbd57ecc19c6.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.api.hou_api.render_thumb', 'id': 'a1333a7a-1192-467a-a7a5-ae1e623c4a87', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'a1333a7a-1192-467a-a7a5-ae1e623c4a87', 'parent_id': None, 'argsrepr': "('/root/hip_storage/636f0ab4-43df-43d7-825d-95b55ef8efd0.hiplc', '/obj/test', '72c73f65-7004-4194-8350-dbd57ecc19c6.png')", 'kwargsrepr': '{}', 'origin': 'gen309@b95d2f005950', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.api.hou_api.render_thumb'
[2023-12-13 06:40:27,280: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:40:27,286: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 06:40:27,286: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:40:27,287: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 06:40:27,290: INFO/MainProcess] sync with celery@b95d2f005950
[2023-12-13 06:40:28,294: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@b95d2f005950.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2023-12-13 06:40:28,294: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 06:40:28,294: INFO/MainProcess] mingle: sync complete
[2023-12-13 06:40:28,302: INFO/MainProcess] celery@b95d2f005950 ready.
[2023-12-13 06:40:38,370: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:40:38,376: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 06:40:38,376: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:40:38,377: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 06:40:38,380: INFO/MainProcess] sync with celery@b95d2f005950
[2023-12-13 06:40:39,383: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@b95d2f005950.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2023-12-13 06:40:39,383: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 06:40:39,384: INFO/MainProcess] mingle: sync complete
[2023-12-13 06:40:39,390: INFO/MainProcess] celery@b95d2f005950 ready.
[2023-12-13 06:41:20,812: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:41:20,819: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 06:41:20,819: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:41:20,821: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 06:41:21,826: INFO/MainProcess] mingle: all alone
[2023-12-13 06:41:21,833: INFO/MainProcess] celery@d2e1e9846bbd ready.
[2023-12-13 06:42:22,150: ERROR/MainProcess] Received unregistered task of type 'app.api.hou_api.render_thumb'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/05c3660b-22b5-4469-9eb7-d839933592e5.hiplc", "/obj/test", "ba90dfbc-c558-4c73-bfdf-4f419af64259.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.api.hou_api.render_thumb', 'id': '0865594d-937f-4075-b61e-fe76ccb80c61', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '0865594d-937f-4075-b61e-fe76ccb80c61', 'parent_id': None, 'argsrepr': "('/root/hip_storage/05c3660b-22b5-4469-9eb7-d839933592e5.hiplc', '/obj/test', 'ba90dfbc-c558-4c73-bfdf-4f419af64259.png')", 'kwargsrepr': '{}', 'origin': 'gen81@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.api.hou_api.render_thumb'
[2023-12-13 06:46:17,587: ERROR/MainProcess] Received unregistered task of type 'app.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["hiii"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (83b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.run_task', 'id': '0dae9f0e-f402-4de9-9635-025fcd68804f', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '0dae9f0e-f402-4de9-9635-025fcd68804f', 'parent_id': None, 'argsrepr': "('hiii',)", 'kwargsrepr': '{}', 'origin': 'gen141@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.run_task'
[2023-12-13 06:47:24,159: ERROR/MainProcess] Received unregistered task of type 'app.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["hiii"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (83b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.run_task', 'id': '6306259b-8c58-4c5e-8639-366b702dd028', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '6306259b-8c58-4c5e-8639-366b702dd028', 'parent_id': None, 'argsrepr': "('hiii',)", 'kwargsrepr': '{}', 'origin': 'gen183@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.run_task'
[2023-12-13 06:48:04,702: ERROR/MainProcess] Received unregistered task of type 'app.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["hiii"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (83b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.run_task', 'id': 'a2fe9ae9-d7e4-40b4-8b93-1642c03fa51d', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'a2fe9ae9-d7e4-40b4-8b93-1642c03fa51d', 'parent_id': None, 'argsrepr': "('hiii',)", 'kwargsrepr': '{}', 'origin': 'gen223@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.run_task'
[2023-12-13 06:48:44,009: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:48:44,015: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 06:48:44,016: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:48:44,018: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 06:48:44,020: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 06:48:45,023: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 06:48:45,023: INFO/MainProcess] mingle: sync complete
[2023-12-13 06:48:45,031: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 06:48:53,959: INFO/MainProcess] Task app.run_task[1cf2049c-439b-4829-aadd-65aa7ef8fb3a] received
[2023-12-13 06:48:53,960: WARNING/ForkPoolWorker-15] Running hiii. Received...
[2023-12-13 06:48:53,961: WARNING/ForkPoolWorker-15] - args: ()
[2023-12-13 06:48:53,961: WARNING/ForkPoolWorker-15] - kwargs: {}
[2023-12-13 06:48:53,961: INFO/ForkPoolWorker-15] Task app.run_task[1cf2049c-439b-4829-aadd-65aa7ef8fb3a] succeeded in 0.0006070750005164882s: None
[2023-12-13 06:49:04,061: ERROR/MainProcess] Received unregistered task of type 'app.api.hou_api.render_thumb'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/c0675fd0-df07-4b1f-bf5a-d76903e85f5d.hiplc", "/obj/test", "bac74365-1832-4ff0-9e93-634a25a772ff.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.api.hou_api.render_thumb', 'id': 'a1ff6e02-a48a-46f6-92cb-0c07fd33f11a', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'a1ff6e02-a48a-46f6-92cb-0c07fd33f11a', 'parent_id': None, 'argsrepr': "('/root/hip_storage/c0675fd0-df07-4b1f-bf5a-d76903e85f5d.hiplc', '/obj/test', 'bac74365-1832-4ff0-9e93-634a25a772ff.png')", 'kwargsrepr': '{}', 'origin': 'gen296@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.api.hou_api.render_thumb'
[2023-12-13 06:51:19,606: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:51:19,612: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 06:51:19,612: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:51:19,613: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 06:51:19,616: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 06:51:20,619: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 06:51:20,620: INFO/MainProcess] mingle: sync complete
[2023-12-13 06:51:20,627: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 06:51:22,428: ERROR/MainProcess] Received unregistered task of type 'app.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["hiii"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (83b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.run_task', 'id': '60ec6889-0f6a-43aa-a311-af25c0d17259', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '60ec6889-0f6a-43aa-a311-af25c0d17259', 'parent_id': None, 'argsrepr': "('hiii',)", 'kwargsrepr': '{}', 'origin': 'gen379@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.run_task'
[2023-12-13 06:51:39,559: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:51:39,565: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 06:51:39,566: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:51:39,567: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 06:51:39,570: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 06:51:40,572: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 06:51:40,572: INFO/MainProcess] mingle: sync complete
[2023-12-13 06:51:40,580: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 06:51:43,565: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:51:43,571: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 06:51:43,571: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:51:43,572: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 06:51:43,575: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 06:51:44,578: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 06:51:44,578: INFO/MainProcess] mingle: sync complete
[2023-12-13 06:51:44,585: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 06:51:47,789: ERROR/MainProcess] Received unregistered task of type 'app.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["hiii"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (83b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.run_task', 'id': 'dc0cdbd2-874d-4dca-8367-28e3774775b1', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'dc0cdbd2-874d-4dca-8367-28e3774775b1', 'parent_id': None, 'argsrepr': "('hiii',)", 'kwargsrepr': '{}', 'origin': 'gen467@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.run_task'
[2023-12-13 06:52:14,050: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:52:14,056: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 06:52:14,057: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:52:14,059: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 06:52:14,061: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 06:52:15,064: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 06:52:15,064: INFO/MainProcess] mingle: sync complete
[2023-12-13 06:52:15,070: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 06:52:16,974: INFO/MainProcess] Task app.run_task[51d44de4-fc5e-47c1-bf5e-d69e871341a4] received
[2023-12-13 06:52:16,975: WARNING/ForkPoolWorker-15] farts
[2023-12-13 06:52:16,975: INFO/ForkPoolWorker-15] Task app.run_task[51d44de4-fc5e-47c1-bf5e-d69e871341a4] succeeded in 0.0006345249985315604s: None
[2023-12-13 06:52:36,911: ERROR/MainProcess] Received unregistered task of type 'app.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.run_task', 'id': '43edbe00-f4d3-4009-b335-03b01379e787', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '43edbe00-f4d3-4009-b335-03b01379e787', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen566@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.run_task'
[2023-12-13 06:53:49,379: ERROR/MainProcess] Received unregistered task of type 'app.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.run_task', 'id': '70ec6abe-4b5c-437e-9758-699dd1bf0712', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '70ec6abe-4b5c-437e-9758-699dd1bf0712', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen604@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.run_task'
[2023-12-13 06:53:55,647: ERROR/MainProcess] Received unregistered task of type 'app.api.hou_api.render_thumb'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc", "/obj/test", "bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.api.hou_api.render_thumb', 'id': 'a83a501f-c2af-4508-a4a2-46e8bce6141f', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'a83a501f-c2af-4508-a4a2-46e8bce6141f', 'parent_id': None, 'argsrepr': "('/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc', '/obj/test', 'bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png')", 'kwargsrepr': '{}', 'origin': 'gen604@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.api.hou_api.render_thumb'
[2023-12-13 06:55:52,401: ERROR/MainProcess] Received unregistered task of type 'app.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc", "/obj/test", "bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.run_task', 'id': '67c5847b-522a-43ee-8dc4-35162a1b0099', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '67c5847b-522a-43ee-8dc4-35162a1b0099', 'parent_id': None, 'argsrepr': "('/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc', '/obj/test', 'bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png')", 'kwargsrepr': '{}', 'origin': 'gen666@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.run_task'
[2023-12-13 06:55:59,813: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:55:59,819: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 06:55:59,820: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:55:59,821: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 06:55:59,824: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 06:56:00,826: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 06:56:00,826: INFO/MainProcess] mingle: sync complete
[2023-12-13 06:56:00,833: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 06:57:44,156: ERROR/MainProcess] Received unregistered task of type 'app.test_run'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc", "/obj/test", "bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.test_run', 'id': '91fb24eb-f106-4abb-836d-8b99808fc0c0', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '91fb24eb-f106-4abb-836d-8b99808fc0c0', 'parent_id': None, 'argsrepr': "('/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc', '/obj/test', 'bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png')", 'kwargsrepr': '{}', 'origin': 'gen733@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.test_run'
[2023-12-13 06:57:49,770: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:57:49,776: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 06:57:49,776: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:57:49,777: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 06:57:49,780: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 06:57:50,782: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 06:57:50,783: INFO/MainProcess] mingle: sync complete
[2023-12-13 06:57:50,790: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 06:58:46,880: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:58:46,886: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 06:58:46,887: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:58:46,889: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 06:58:46,893: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 06:58:47,895: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 06:58:47,896: INFO/MainProcess] mingle: sync complete
[2023-12-13 06:58:47,902: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 06:58:50,067: ERROR/MainProcess] Received unregistered task of type 'app.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc", "/obj/test", "bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.run_task', 'id': 'b6265e18-2596-4bd4-b335-3266e6f94f1f', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'b6265e18-2596-4bd4-b335-3266e6f94f1f', 'parent_id': None, 'argsrepr': "('/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc', '/obj/test', 'bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png')", 'kwargsrepr': '{}', 'origin': 'gen823@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.run_task'
[2023-12-13 06:59:58,644: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:59:58,651: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 06:59:58,652: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 06:59:58,654: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 06:59:58,658: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 06:59:59,661: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 06:59:59,661: INFO/MainProcess] mingle: sync complete
[2023-12-13 06:59:59,666: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 07:00:04,103: ERROR/MainProcess] Received unregistered task of type 'app.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc", "/obj/test", "bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.run_task', 'id': '82ac1ad7-1948-488e-93ba-0e6acfa2913d', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '82ac1ad7-1948-488e-93ba-0e6acfa2913d', 'parent_id': None, 'argsrepr': "('/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc', '/obj/test', 'bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png')", 'kwargsrepr': '{}', 'origin': 'gen887@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.run_task'
[2023-12-13 07:00:37,739: ERROR/MainProcess] Received unregistered task of type 'run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc", "/obj/test", "bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'run_task', 'id': '1477fc4f-d1f7-4cb2-92a3-6661b778c1a5', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '1477fc4f-d1f7-4cb2-92a3-6661b778c1a5', 'parent_id': None, 'argsrepr': "('/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc', '/obj/test', 'bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png')", 'kwargsrepr': '{}', 'origin': 'gen924@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'run_task'
[2023-12-13 07:02:38,852: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2023-12-13 07:02:38,853: DEBUG/MainProcess] | Worker: Building graph...
[2023-12-13 07:02:38,854: DEBUG/MainProcess] | Worker: New boot order: {Beat, Timer, Hub, Pool, Autoscaler, StateDB, Consumer}
[2023-12-13 07:02:38,856: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2023-12-13 07:02:38,856: DEBUG/MainProcess] | Consumer: Building graph...
[2023-12-13 07:02:38,861: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Agent, Events, Mingle, Gossip, Heart, Tasks, Control, event loop}
[2023-12-13 07:02:38,870: DEBUG/MainProcess] | Worker: Starting Hub
[2023-12-13 07:02:38,870: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:02:38,870: DEBUG/MainProcess] | Worker: Starting Pool
[2023-12-13 07:02:39,223: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:02:39,224: DEBUG/MainProcess] | Worker: Starting Consumer
[2023-12-13 07:02:39,224: DEBUG/MainProcess] | Consumer: Starting Connection
[2023-12-13 07:02:39,225: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:02:39,230: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 07:02:39,230: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:02:39,230: DEBUG/MainProcess] | Consumer: Starting Events
[2023-12-13 07:02:39,230: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:02:39,231: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:02:39,231: DEBUG/MainProcess] | Consumer: Starting Mingle
[2023-12-13 07:02:39,231: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 07:02:39,234: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 07:02:40,237: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 07:02:40,237: DEBUG/MainProcess] mingle: processing reply from celery@d2e1e9846bbd
[2023-12-13 07:02:40,237: INFO/MainProcess] mingle: sync complete
[2023-12-13 07:02:40,237: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:02:40,237: DEBUG/MainProcess] | Consumer: Starting Gossip
[2023-12-13 07:02:40,239: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:02:40,239: DEBUG/MainProcess] | Consumer: Starting Heart
[2023-12-13 07:02:40,240: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:02:40,240: DEBUG/MainProcess] | Consumer: Starting Tasks
[2023-12-13 07:02:40,242: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:02:40,242: DEBUG/MainProcess] | Consumer: Starting Control
[2023-12-13 07:02:40,243: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:02:40,243: DEBUG/MainProcess] | Consumer: Starting event loop
[2023-12-13 07:02:40,243: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2023-12-13 07:02:40,244: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 07:02:40,244: DEBUG/MainProcess] basic.qos: prefetch_count->96
[2023-12-13 07:02:42,068: DEBUG/MainProcess] celery@d2e1e9846bbd joined the party
[2023-12-13 07:02:48,350: ERROR/MainProcess] Received unregistered task of type 'run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc", "/obj/test", "bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'run_task', 'id': 'e64ec09e-539f-4f32-8620-9b893eaddecf', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'e64ec09e-539f-4f32-8620-9b893eaddecf', 'parent_id': None, 'argsrepr': "('/root/hip_storage/02536bdc-33e7-473f-a8a2-54df3a61fa66.hiplc', '/obj/test', 'bbd77955-ec3e-4df6-9adc-b5a01ef27e13.png')", 'kwargsrepr': '{}', 'origin': 'gen991@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'run_task'
[2023-12-13 07:07:15,071: DEBUG/MainProcess] | Worker: Closing Hub...
[2023-12-13 07:07:15,071: DEBUG/MainProcess] | Worker: Closing Pool...
[2023-12-13 07:07:15,071: DEBUG/MainProcess] | Worker: Closing Consumer...
[2023-12-13 07:07:15,071: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2023-12-13 07:07:15,071: DEBUG/MainProcess] | Consumer: Closing Connection...
[2023-12-13 07:07:15,071: DEBUG/MainProcess] | Consumer: Closing Events...
[2023-12-13 07:07:15,072: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2023-12-13 07:07:15,072: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2023-12-13 07:07:15,072: DEBUG/MainProcess] | Consumer: Closing Heart...
[2023-12-13 07:07:15,072: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2023-12-13 07:07:15,072: DEBUG/MainProcess] | Consumer: Closing Control...
[2023-12-13 07:07:15,072: DEBUG/MainProcess] | Consumer: Closing event loop...
[2023-12-13 07:07:15,072: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2023-12-13 07:07:15,072: DEBUG/MainProcess] | Consumer: Stopping Control...
[2023-12-13 07:07:15,074: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2023-12-13 07:07:15,074: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:07:15,074: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2023-12-13 07:07:15,075: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2023-12-13 07:07:15,076: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2023-12-13 07:07:15,076: DEBUG/MainProcess] | Consumer: Stopping Events...
[2023-12-13 07:07:15,076: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2023-12-13 07:07:15,076: DEBUG/MainProcess] | Worker: Stopping Pool...
[2023-12-13 07:07:16,090: DEBUG/MainProcess] | Worker: Stopping Hub...
[2023-12-13 07:07:16,091: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2023-12-13 07:07:16,091: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2023-12-13 07:07:16,091: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:07:16,091: DEBUG/MainProcess] Closing consumer channel...
[2023-12-13 07:07:16,091: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2023-12-13 07:07:16,091: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2023-12-13 07:07:16,091: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2023-12-13 07:07:16,091: DEBUG/MainProcess] | Consumer: Shutdown Connection...
[2023-12-13 07:07:16,092: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
[2023-12-13 07:07:17,529: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2023-12-13 07:07:17,531: DEBUG/MainProcess] | Worker: Building graph...
[2023-12-13 07:07:17,531: DEBUG/MainProcess] | Worker: New boot order: {StateDB, Beat, Timer, Hub, Pool, Autoscaler, Consumer}
[2023-12-13 07:07:17,533: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2023-12-13 07:07:17,533: DEBUG/MainProcess] | Consumer: Building graph...
[2023-12-13 07:07:17,539: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Heart, Agent, Mingle, Tasks, Control, Gossip, event loop}
[2023-12-13 07:07:17,548: DEBUG/MainProcess] | Worker: Starting Hub
[2023-12-13 07:07:17,548: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:07:17,548: DEBUG/MainProcess] | Worker: Starting Pool
[2023-12-13 07:07:17,880: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:07:17,881: DEBUG/MainProcess] | Worker: Starting Consumer
[2023-12-13 07:07:17,881: DEBUG/MainProcess] | Consumer: Starting Connection
[2023-12-13 07:07:17,882: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:07:17,887: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 07:07:17,887: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:07:17,887: DEBUG/MainProcess] | Consumer: Starting Events
[2023-12-13 07:07:17,888: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:07:17,889: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:07:17,889: DEBUG/MainProcess] | Consumer: Starting Heart
[2023-12-13 07:07:17,890: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:07:17,890: DEBUG/MainProcess] | Consumer: Starting Mingle
[2023-12-13 07:07:17,890: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 07:07:17,892: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 07:07:18,895: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 07:07:18,895: DEBUG/MainProcess] mingle: processing reply from celery@d2e1e9846bbd
[2023-12-13 07:07:18,895: INFO/MainProcess] mingle: sync complete
[2023-12-13 07:07:18,895: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:07:18,895: DEBUG/MainProcess] | Consumer: Starting Tasks
[2023-12-13 07:07:18,897: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:07:18,897: DEBUG/MainProcess] | Consumer: Starting Control
[2023-12-13 07:07:18,899: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:07:18,899: DEBUG/MainProcess] | Consumer: Starting Gossip
[2023-12-13 07:07:18,900: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:07:18,900: DEBUG/MainProcess] | Consumer: Starting event loop
[2023-12-13 07:07:18,900: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2023-12-13 07:07:18,901: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 07:07:18,901: DEBUG/MainProcess] basic.qos: prefetch_count->96
[2023-12-13 07:07:20,334: DEBUG/MainProcess] celery@d2e1e9846bbd joined the party
[2023-12-13 07:08:11,830: ERROR/MainProcess] Received unregistered task of type 'run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/8093bb52-32df-4684-b021-3e3f884f5b95.hiplc", "/obj/test", "25856361-f186-4afe-897e-4cd0aaa61c9e.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'run_task', 'id': '4b7d97ff-f90b-4715-99d2-7467abdc09f2', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '4b7d97ff-f90b-4715-99d2-7467abdc09f2', 'parent_id': None, 'argsrepr': "('/root/hip_storage/8093bb52-32df-4684-b021-3e3f884f5b95.hiplc', '/obj/test', '25856361-f186-4afe-897e-4cd0aaa61c9e.png')", 'kwargsrepr': '{}', 'origin': 'gen1034@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'run_task'
[2023-12-13 07:08:53,925: DEBUG/MainProcess] | Worker: Closing Hub...
[2023-12-13 07:08:53,925: DEBUG/MainProcess] | Worker: Closing Pool...
[2023-12-13 07:08:53,925: DEBUG/MainProcess] | Worker: Closing Consumer...
[2023-12-13 07:08:53,925: DEBUG/MainProcess] | Worker: Terminating Consumer...
[2023-12-13 07:08:53,925: DEBUG/MainProcess] | Consumer: Closing Connection...
[2023-12-13 07:08:53,925: DEBUG/MainProcess] | Consumer: Closing Events...
[2023-12-13 07:08:53,925: DEBUG/MainProcess] | Consumer: Closing Heart...
[2023-12-13 07:08:53,926: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2023-12-13 07:08:53,926: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2023-12-13 07:08:53,926: DEBUG/MainProcess] | Consumer: Closing Control...
[2023-12-13 07:08:53,926: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2023-12-13 07:08:53,926: DEBUG/MainProcess] | Consumer: Closing event loop...
[2023-12-13 07:08:53,926: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2023-12-13 07:08:53,926: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2023-12-13 07:08:53,927: DEBUG/MainProcess] | Consumer: Stopping Control...
[2023-12-13 07:08:53,928: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2023-12-13 07:08:53,928: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:08:53,928: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2023-12-13 07:08:53,928: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2023-12-13 07:08:53,928: DEBUG/MainProcess] | Consumer: Stopping Events...
[2023-12-13 07:08:53,928: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2023-12-13 07:08:53,929: DEBUG/MainProcess] | Worker: Terminating Pool...
[2023-12-13 07:08:53,929: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
[2023-12-13 07:08:55,446: DEBUG/MainProcess] | Worker: Terminating Hub...
[2023-12-13 07:08:55,447: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2023-12-13 07:08:55,447: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2023-12-13 07:08:55,447: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2023-12-13 07:08:55,447: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:08:55,447: DEBUG/MainProcess] Closing consumer channel...
[2023-12-13 07:08:55,447: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2023-12-13 07:08:55,447: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2023-12-13 07:08:55,447: DEBUG/MainProcess] | Consumer: Shutdown Connection...
[2023-12-13 07:08:56,197: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2023-12-13 07:08:56,199: DEBUG/MainProcess] | Worker: Building graph...
[2023-12-13 07:08:56,199: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Pool, Autoscaler, StateDB, Beat, Consumer}
[2023-12-13 07:08:56,201: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2023-12-13 07:08:56,202: DEBUG/MainProcess] | Consumer: Building graph...
[2023-12-13 07:08:56,207: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Heart, Mingle, Tasks, Control, Gossip, Agent, event loop}
[2023-12-13 07:08:56,216: DEBUG/MainProcess] | Worker: Starting Hub
[2023-12-13 07:08:56,216: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:08:56,217: DEBUG/MainProcess] | Worker: Starting Pool
[2023-12-13 07:08:56,551: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:08:56,551: DEBUG/MainProcess] | Worker: Starting Consumer
[2023-12-13 07:08:56,552: DEBUG/MainProcess] | Consumer: Starting Connection
[2023-12-13 07:08:56,553: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:08:56,559: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 07:08:56,559: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:08:56,559: DEBUG/MainProcess] | Consumer: Starting Events
[2023-12-13 07:08:56,559: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:08:56,560: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:08:56,560: DEBUG/MainProcess] | Consumer: Starting Heart
[2023-12-13 07:08:56,561: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:08:56,561: DEBUG/MainProcess] | Consumer: Starting Mingle
[2023-12-13 07:08:56,562: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 07:08:56,564: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 07:08:57,567: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 07:08:57,568: DEBUG/MainProcess] mingle: processing reply from celery@d2e1e9846bbd
[2023-12-13 07:08:57,568: INFO/MainProcess] mingle: sync complete
[2023-12-13 07:08:57,568: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:08:57,568: DEBUG/MainProcess] | Consumer: Starting Tasks
[2023-12-13 07:08:57,570: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:08:57,570: DEBUG/MainProcess] | Consumer: Starting Control
[2023-12-13 07:08:57,572: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:08:57,572: DEBUG/MainProcess] | Consumer: Starting Gossip
[2023-12-13 07:08:57,574: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:08:57,574: DEBUG/MainProcess] | Consumer: Starting event loop
[2023-12-13 07:08:57,574: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2023-12-13 07:08:57,575: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 07:08:57,575: DEBUG/MainProcess] basic.qos: prefetch_count->96
[2023-12-13 07:08:58,413: DEBUG/MainProcess] celery@d2e1e9846bbd joined the party
[2023-12-13 07:09:07,195: ERROR/MainProcess] Received unregistered task of type 'app.tasks.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/432bfb3c-3ff9-469c-8859-e966134489cc.hiplc", "/obj/test", "4b9879c8-e79e-4ba7-ae20-ccf153f5e2af.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.tasks.run_task', 'id': '236839a9-2456-404b-ab47-e2946a6b7a2f', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '236839a9-2456-404b-ab47-e2946a6b7a2f', 'parent_id': None, 'argsrepr': "('/root/hip_storage/432bfb3c-3ff9-469c-8859-e966134489cc.hiplc', '/obj/test', '4b9879c8-e79e-4ba7-ae20-ccf153f5e2af.png')", 'kwargsrepr': '{}', 'origin': 'gen1121@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.tasks.run_task'
[2023-12-13 07:10:24,493: DEBUG/MainProcess] | Worker: Closing Hub...
[2023-12-13 07:10:24,493: DEBUG/MainProcess] | Worker: Closing Pool...
[2023-12-13 07:10:24,494: DEBUG/MainProcess] | Worker: Closing Consumer...
[2023-12-13 07:10:24,494: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2023-12-13 07:10:24,494: DEBUG/MainProcess] | Consumer: Closing Connection...
[2023-12-13 07:10:24,494: DEBUG/MainProcess] | Consumer: Closing Events...
[2023-12-13 07:10:24,494: DEBUG/MainProcess] | Consumer: Closing Heart...
[2023-12-13 07:10:24,494: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2023-12-13 07:10:24,494: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2023-12-13 07:10:24,494: DEBUG/MainProcess] | Consumer: Closing Control...
[2023-12-13 07:10:24,494: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2023-12-13 07:10:24,494: DEBUG/MainProcess] | Consumer: Closing event loop...
[2023-12-13 07:10:24,494: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2023-12-13 07:10:24,494: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2023-12-13 07:10:24,496: DEBUG/MainProcess] | Consumer: Stopping Control...
[2023-12-13 07:10:24,498: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2023-12-13 07:10:24,498: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:10:24,498: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2023-12-13 07:10:24,498: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2023-12-13 07:10:24,499: DEBUG/MainProcess] | Consumer: Stopping Events...
[2023-12-13 07:10:24,499: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2023-12-13 07:10:24,499: DEBUG/MainProcess] | Worker: Stopping Pool...
[2023-12-13 07:10:25,514: DEBUG/MainProcess] | Worker: Stopping Hub...
[2023-12-13 07:10:25,514: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2023-12-13 07:10:25,514: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2023-12-13 07:10:25,514: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2023-12-13 07:10:25,514: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:10:25,515: DEBUG/MainProcess] Closing consumer channel...
[2023-12-13 07:10:25,515: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2023-12-13 07:10:25,515: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2023-12-13 07:10:25,515: DEBUG/MainProcess] | Consumer: Shutdown Connection...
[2023-12-13 07:10:25,515: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
[2023-12-13 07:10:26,853: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2023-12-13 07:10:26,855: DEBUG/MainProcess] | Worker: Building graph...
[2023-12-13 07:10:26,855: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Pool, Autoscaler, Beat, StateDB, Consumer}
[2023-12-13 07:10:26,857: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2023-12-13 07:10:26,857: DEBUG/MainProcess] | Consumer: Building graph...
[2023-12-13 07:10:26,863: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Agent, Events, Heart, Mingle, Gossip, Tasks, Control, event loop}
[2023-12-13 07:10:26,871: DEBUG/MainProcess] | Worker: Starting Hub
[2023-12-13 07:10:26,871: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:10:26,871: DEBUG/MainProcess] | Worker: Starting Pool
[2023-12-13 07:10:27,211: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:10:27,211: DEBUG/MainProcess] | Worker: Starting Consumer
[2023-12-13 07:10:27,211: DEBUG/MainProcess] | Consumer: Starting Connection
[2023-12-13 07:10:27,212: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:10:27,218: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 07:10:27,218: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:10:27,218: DEBUG/MainProcess] | Consumer: Starting Events
[2023-12-13 07:10:27,218: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:10:27,219: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:10:27,219: DEBUG/MainProcess] | Consumer: Starting Heart
[2023-12-13 07:10:27,220: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:10:27,220: DEBUG/MainProcess] | Consumer: Starting Mingle
[2023-12-13 07:10:27,220: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 07:10:27,223: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 07:10:28,225: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 07:10:28,226: DEBUG/MainProcess] mingle: processing reply from celery@d2e1e9846bbd
[2023-12-13 07:10:28,226: INFO/MainProcess] mingle: sync complete
[2023-12-13 07:10:28,226: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:10:28,226: DEBUG/MainProcess] | Consumer: Starting Gossip
[2023-12-13 07:10:28,228: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:10:28,228: DEBUG/MainProcess] | Consumer: Starting Tasks
[2023-12-13 07:10:28,230: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:10:28,230: DEBUG/MainProcess] | Consumer: Starting Control
[2023-12-13 07:10:28,232: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:10:28,232: DEBUG/MainProcess] | Consumer: Starting event loop
[2023-12-13 07:10:28,232: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2023-12-13 07:10:28,232: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 07:10:28,232: DEBUG/MainProcess] basic.qos: prefetch_count->96
[2023-12-13 07:10:28,498: DEBUG/MainProcess] celery@d2e1e9846bbd joined the party
[2023-12-13 07:10:34,331: ERROR/MainProcess] Received unregistered task of type 'app.tasks.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/0e2ac360-5f0d-4dae-90f4-a240cfcfdbdc.hiplc", "/obj/test", "2dc9c0be-70da-4a65-a195-bb039d3b38ff.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.tasks.run_task', 'id': 'e9898c90-5038-455a-ad62-2a750489dcb1', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'e9898c90-5038-455a-ad62-2a750489dcb1', 'parent_id': None, 'argsrepr': "('/root/hip_storage/0e2ac360-5f0d-4dae-90f4-a240cfcfdbdc.hiplc', '/obj/test', '2dc9c0be-70da-4a65-a195-bb039d3b38ff.png')", 'kwargsrepr': '{}', 'origin': 'gen1208@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.tasks.run_task'
[2023-12-13 07:11:12,365: DEBUG/MainProcess] | Worker: Closing Hub...
[2023-12-13 07:11:12,365: DEBUG/MainProcess] | Worker: Closing Pool...
[2023-12-13 07:11:12,366: DEBUG/MainProcess] | Worker: Closing Consumer...
[2023-12-13 07:11:12,366: DEBUG/MainProcess] | Worker: Terminating Consumer...
[2023-12-13 07:11:12,366: DEBUG/MainProcess] | Consumer: Closing Connection...
[2023-12-13 07:11:12,366: DEBUG/MainProcess] | Consumer: Closing Events...
[2023-12-13 07:11:12,366: DEBUG/MainProcess] | Consumer: Closing Heart...
[2023-12-13 07:11:12,366: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2023-12-13 07:11:12,366: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2023-12-13 07:11:12,366: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2023-12-13 07:11:12,366: DEBUG/MainProcess] | Consumer: Closing Control...
[2023-12-13 07:11:12,366: DEBUG/MainProcess] | Consumer: Closing event loop...
[2023-12-13 07:11:12,366: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2023-12-13 07:11:12,366: DEBUG/MainProcess] | Consumer: Stopping Control...
[2023-12-13 07:11:12,368: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2023-12-13 07:11:12,368: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:11:12,368: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2023-12-13 07:11:12,369: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2023-12-13 07:11:12,369: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2023-12-13 07:11:12,369: DEBUG/MainProcess] | Consumer: Stopping Events...
[2023-12-13 07:11:12,370: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2023-12-13 07:11:12,370: DEBUG/MainProcess] | Worker: Terminating Pool...
[2023-12-13 07:11:12,370: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
[2023-12-13 07:11:13,887: DEBUG/MainProcess] | Worker: Terminating Hub...
[2023-12-13 07:11:13,887: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2023-12-13 07:11:13,887: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2023-12-13 07:11:13,887: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:11:13,888: DEBUG/MainProcess] Closing consumer channel...
[2023-12-13 07:11:13,888: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2023-12-13 07:11:13,888: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2023-12-13 07:11:13,888: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2023-12-13 07:11:13,888: DEBUG/MainProcess] | Consumer: Shutdown Connection...
[2023-12-13 07:11:14,158: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2023-12-13 07:11:14,160: DEBUG/MainProcess] | Worker: Building graph...
[2023-12-13 07:11:14,160: DEBUG/MainProcess] | Worker: New boot order: {StateDB, Beat, Timer, Hub, Pool, Autoscaler, Consumer}
[2023-12-13 07:11:14,162: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2023-12-13 07:11:14,162: DEBUG/MainProcess] | Consumer: Building graph...
[2023-12-13 07:11:14,168: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Agent, Events, Mingle, Tasks, Control, Heart, Gossip, event loop}
[2023-12-13 07:11:14,177: DEBUG/MainProcess] | Worker: Starting Hub
[2023-12-13 07:11:14,177: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:11:14,177: DEBUG/MainProcess] | Worker: Starting Pool
[2023-12-13 07:11:14,524: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:11:14,524: DEBUG/MainProcess] | Worker: Starting Consumer
[2023-12-13 07:11:14,524: DEBUG/MainProcess] | Consumer: Starting Connection
[2023-12-13 07:11:14,525: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:11:14,530: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 07:11:14,530: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:11:14,530: DEBUG/MainProcess] | Consumer: Starting Events
[2023-12-13 07:11:14,530: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:11:14,531: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:11:14,531: DEBUG/MainProcess] | Consumer: Starting Mingle
[2023-12-13 07:11:14,531: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 07:11:14,534: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 07:11:15,537: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 07:11:15,537: DEBUG/MainProcess] mingle: processing reply from celery@d2e1e9846bbd
[2023-12-13 07:11:15,537: INFO/MainProcess] mingle: sync complete
[2023-12-13 07:11:15,537: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:11:15,537: DEBUG/MainProcess] | Consumer: Starting Tasks
[2023-12-13 07:11:15,539: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:11:15,539: DEBUG/MainProcess] | Consumer: Starting Control
[2023-12-13 07:11:15,540: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:11:15,541: DEBUG/MainProcess] | Consumer: Starting Heart
[2023-12-13 07:11:15,541: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:11:15,541: DEBUG/MainProcess] | Consumer: Starting Gossip
[2023-12-13 07:11:15,543: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:11:15,543: DEBUG/MainProcess] | Consumer: Starting event loop
[2023-12-13 07:11:15,543: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2023-12-13 07:11:15,543: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 07:11:15,544: DEBUG/MainProcess] basic.qos: prefetch_count->96
[2023-12-13 07:11:16,534: DEBUG/MainProcess] celery@d2e1e9846bbd joined the party
[2023-12-13 07:11:21,332: ERROR/MainProcess] Received unregistered task of type 'tasks.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/6a08b735-7524-45df-ad26-e7361c27dfe7.hiplc", "/obj/test", "2858feb5-0b28-42ac-ba3c-6ddc5e648d25.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'tasks.run_task', 'id': 'c9b2bc31-2fab-49b1-a901-eb811715fbbf', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'c9b2bc31-2fab-49b1-a901-eb811715fbbf', 'parent_id': None, 'argsrepr': "('/root/hip_storage/6a08b735-7524-45df-ad26-e7361c27dfe7.hiplc', '/obj/test', '2858feb5-0b28-42ac-ba3c-6ddc5e648d25.png')", 'kwargsrepr': '{}', 'origin': 'gen1293@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'tasks.run_task'
[2023-12-13 07:12:01,592: DEBUG/MainProcess] | Worker: Closing Hub...
[2023-12-13 07:12:01,592: DEBUG/MainProcess] | Worker: Closing Pool...
[2023-12-13 07:12:01,592: DEBUG/MainProcess] | Worker: Closing Consumer...
[2023-12-13 07:12:01,592: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2023-12-13 07:12:01,592: DEBUG/MainProcess] | Consumer: Closing Connection...
[2023-12-13 07:12:01,592: DEBUG/MainProcess] | Consumer: Closing Events...
[2023-12-13 07:12:01,593: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2023-12-13 07:12:01,593: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2023-12-13 07:12:01,593: DEBUG/MainProcess] | Consumer: Closing Control...
[2023-12-13 07:12:01,593: DEBUG/MainProcess] | Consumer: Closing Heart...
[2023-12-13 07:12:01,593: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2023-12-13 07:12:01,593: DEBUG/MainProcess] | Consumer: Closing event loop...
[2023-12-13 07:12:01,593: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2023-12-13 07:12:01,593: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2023-12-13 07:12:01,595: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2023-12-13 07:12:01,595: DEBUG/MainProcess] | Consumer: Stopping Control...
[2023-12-13 07:12:01,597: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2023-12-13 07:12:01,597: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:12:01,597: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2023-12-13 07:12:01,597: DEBUG/MainProcess] | Consumer: Stopping Events...
[2023-12-13 07:12:01,597: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2023-12-13 07:12:01,597: DEBUG/MainProcess] | Worker: Stopping Pool...
[2023-12-13 07:12:02,613: DEBUG/MainProcess] | Worker: Stopping Hub...
[2023-12-13 07:12:02,614: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2023-12-13 07:12:02,614: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2023-12-13 07:12:02,614: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2023-12-13 07:12:02,614: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2023-12-13 07:12:02,614: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:12:02,614: DEBUG/MainProcess] Closing consumer channel...
[2023-12-13 07:12:02,614: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2023-12-13 07:12:02,614: DEBUG/MainProcess] | Consumer: Shutdown Connection...
[2023-12-13 07:12:02,615: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
[2023-12-13 07:13:56,645: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2023-12-13 07:13:56,647: DEBUG/MainProcess] | Worker: Building graph...
[2023-12-13 07:13:56,647: DEBUG/MainProcess] | Worker: New boot order: {Beat, Timer, Hub, Pool, Autoscaler, StateDB, Consumer}
[2023-12-13 07:13:56,649: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2023-12-13 07:13:56,650: DEBUG/MainProcess] | Consumer: Building graph...
[2023-12-13 07:13:56,655: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Agent, Events, Mingle, Tasks, Control, Gossip, Heart, event loop}
[2023-12-13 07:13:56,665: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/app/utils.py:203: CDeprecationWarning: 
    The 'CELERY_IMPORTS' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the imports instead

  deprecated.warn(description=f'The {setting!r} setting',

[2023-12-13 07:13:56,665: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2023-12-13 07:13:56,665: DEBUG/MainProcess] | Worker: Starting Hub
[2023-12-13 07:13:56,665: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:13:56,665: DEBUG/MainProcess] | Worker: Starting Pool
[2023-12-13 07:13:57,033: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:13:57,034: DEBUG/MainProcess] | Worker: Starting Consumer
[2023-12-13 07:13:57,034: DEBUG/MainProcess] | Consumer: Starting Connection
[2023-12-13 07:13:57,035: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:13:57,041: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 07:13:57,041: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:13:57,041: DEBUG/MainProcess] | Consumer: Starting Events
[2023-12-13 07:13:57,041: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:13:57,042: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:13:57,042: DEBUG/MainProcess] | Consumer: Starting Mingle
[2023-12-13 07:13:57,042: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 07:13:57,046: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 07:13:58,049: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 07:13:58,049: DEBUG/MainProcess] mingle: processing reply from celery@d2e1e9846bbd
[2023-12-13 07:13:58,049: INFO/MainProcess] mingle: sync complete
[2023-12-13 07:13:58,049: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:13:58,049: DEBUG/MainProcess] | Consumer: Starting Tasks
[2023-12-13 07:13:58,051: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:13:58,051: DEBUG/MainProcess] | Consumer: Starting Control
[2023-12-13 07:13:58,053: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:13:58,053: DEBUG/MainProcess] | Consumer: Starting Gossip
[2023-12-13 07:13:58,055: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:13:58,055: DEBUG/MainProcess] | Consumer: Starting Heart
[2023-12-13 07:13:58,056: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:13:58,056: DEBUG/MainProcess] | Consumer: Starting event loop
[2023-12-13 07:13:58,056: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2023-12-13 07:13:58,057: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 07:13:58,057: DEBUG/MainProcess] basic.qos: prefetch_count->96
[2023-12-13 07:13:58,685: DEBUG/MainProcess] celery@d2e1e9846bbd joined the party
[2023-12-13 07:14:09,345: ERROR/MainProcess] Received unregistered task of type 'tasks.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/5e7e41a9-6dd9-4e8f-95cc-2e856672d71c.hiplc", "/obj/test", "3e116831-2de1-4a1c-a86a-520feb96806a.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'tasks.run_task', 'id': 'b1a4384d-f95f-4c71-aedf-769421d6d07a', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'b1a4384d-f95f-4c71-aedf-769421d6d07a', 'parent_id': None, 'argsrepr': "('/root/hip_storage/5e7e41a9-6dd9-4e8f-95cc-2e856672d71c.hiplc', '/obj/test', '3e116831-2de1-4a1c-a86a-520feb96806a.png')", 'kwargsrepr': '{}', 'origin': 'gen1416@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'tasks.run_task'
[2023-12-13 07:14:50,260: DEBUG/MainProcess] | Worker: Closing Hub...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Worker: Closing Pool...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Worker: Closing Consumer...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Consumer: Closing Connection...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Consumer: Closing Events...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Consumer: Closing Control...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Consumer: Closing Heart...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Consumer: Closing event loop...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2023-12-13 07:14:50,261: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2023-12-13 07:14:50,262: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2023-12-13 07:14:50,263: DEBUG/MainProcess] | Consumer: Stopping Control...
[2023-12-13 07:14:50,264: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2023-12-13 07:14:50,265: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:14:50,265: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2023-12-13 07:14:50,265: DEBUG/MainProcess] | Consumer: Stopping Events...
[2023-12-13 07:14:50,265: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2023-12-13 07:14:50,265: DEBUG/MainProcess] | Worker: Stopping Pool...
[2023-12-13 07:14:51,282: DEBUG/MainProcess] | Worker: Stopping Hub...
[2023-12-13 07:14:51,282: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2023-12-13 07:14:51,282: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2023-12-13 07:14:51,282: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2023-12-13 07:14:51,282: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2023-12-13 07:14:51,282: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:14:51,282: DEBUG/MainProcess] Closing consumer channel...
[2023-12-13 07:14:51,282: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2023-12-13 07:14:51,282: DEBUG/MainProcess] | Consumer: Shutdown Connection...
[2023-12-13 07:14:51,283: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
[2023-12-13 07:14:52,453: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2023-12-13 07:14:52,455: DEBUG/MainProcess] | Worker: Building graph...
[2023-12-13 07:14:52,455: DEBUG/MainProcess] | Worker: New boot order: {StateDB, Beat, Timer, Hub, Pool, Autoscaler, Consumer}
[2023-12-13 07:14:52,458: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2023-12-13 07:14:52,458: DEBUG/MainProcess] | Consumer: Building graph...
[2023-12-13 07:14:52,464: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Heart, Agent, Mingle, Tasks, Control, Gossip, event loop}
[2023-12-13 07:14:52,473: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/app/utils.py:203: CDeprecationWarning: 
    The 'CELERY_IMPORTS' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the imports instead

  deprecated.warn(description=f'The {setting!r} setting',

[2023-12-13 07:14:52,473: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2023-12-13 07:14:52,473: DEBUG/MainProcess] | Worker: Starting Hub
[2023-12-13 07:14:52,473: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:14:52,473: DEBUG/MainProcess] | Worker: Starting Pool
[2023-12-13 07:14:52,808: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:14:52,809: DEBUG/MainProcess] | Worker: Starting Consumer
[2023-12-13 07:14:52,809: DEBUG/MainProcess] | Consumer: Starting Connection
[2023-12-13 07:14:52,810: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:14:52,815: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 07:14:52,815: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:14:52,816: DEBUG/MainProcess] | Consumer: Starting Events
[2023-12-13 07:14:52,816: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:14:52,817: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:14:52,817: DEBUG/MainProcess] | Consumer: Starting Heart
[2023-12-13 07:14:52,818: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:14:52,818: DEBUG/MainProcess] | Consumer: Starting Mingle
[2023-12-13 07:14:52,818: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 07:14:52,821: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 07:14:53,824: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 07:14:53,824: DEBUG/MainProcess] mingle: processing reply from celery@d2e1e9846bbd
[2023-12-13 07:14:53,824: INFO/MainProcess] mingle: sync complete
[2023-12-13 07:14:53,824: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:14:53,824: DEBUG/MainProcess] | Consumer: Starting Tasks
[2023-12-13 07:14:53,826: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:14:53,826: DEBUG/MainProcess] | Consumer: Starting Control
[2023-12-13 07:14:53,828: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:14:53,829: DEBUG/MainProcess] | Consumer: Starting Gossip
[2023-12-13 07:14:53,830: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:14:53,830: DEBUG/MainProcess] | Consumer: Starting event loop
[2023-12-13 07:14:53,831: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2023-12-13 07:14:53,831: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 07:14:53,831: DEBUG/MainProcess] basic.qos: prefetch_count->96
[2023-12-13 07:14:54,734: DEBUG/MainProcess] celery@d2e1e9846bbd joined the party
[2023-12-13 07:14:59,817: INFO/MainProcess] Task app.tasks.run_task[1d13dd97-8481-46db-8c3f-2faff42cf087] received
[2023-12-13 07:14:59,817: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7f6d7a8ed670> (args:('app.tasks.run_task', '1d13dd97-8481-46db-8c3f-2faff42cf087', {'lang': 'py', 'task': 'app.tasks.run_task', 'id': '1d13dd97-8481-46db-8c3f-2faff42cf087', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '1d13dd97-8481-46db-8c3f-2faff42cf087', 'parent_id': None, 'argsrepr': "('/root/hip_storage/c082fc2f-0bec-4931-97e3-08e16727179b.hiplc', '/obj/test', '54092b42-3ba2-4bdf-83c1-2d9e36e95b94.png')", 'kwargsrepr': '{}', 'origin': 'gen1467@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}, 'properties': {'correlation_id': '1d13dd97-8481-46db-8c3f-2faff42cf087', 'reply_to': 'd587ccaf-efa2-378d-be21-e05a552f3a11', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'celery'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': '0f3417e4-97f1-4d86-b919-2c73d982fc0d'}, 'reply_to': 'd587ccaf-efa2-378d-be21-e05a552f3a11', 'correlation_id':... kwargs:{})
[2023-12-13 07:14:59,822: INFO/ForkPoolWorker-15] Task app.tasks.run_task[1d13dd97-8481-46db-8c3f-2faff42cf087] succeeded in 0.00427956600105972s: None
[2023-12-13 07:20:09,153: DEBUG/MainProcess] | Worker: Closing Hub...
[2023-12-13 07:20:09,154: DEBUG/MainProcess] | Worker: Closing Pool...
[2023-12-13 07:20:09,154: DEBUG/MainProcess] | Worker: Closing Consumer...
[2023-12-13 07:20:09,154: DEBUG/MainProcess] | Worker: Terminating Consumer...
[2023-12-13 07:20:09,154: DEBUG/MainProcess] | Consumer: Closing Connection...
[2023-12-13 07:20:09,154: DEBUG/MainProcess] | Consumer: Closing Events...
[2023-12-13 07:20:09,154: DEBUG/MainProcess] | Consumer: Closing Heart...
[2023-12-13 07:20:09,155: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2023-12-13 07:20:09,155: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2023-12-13 07:20:09,155: DEBUG/MainProcess] | Consumer: Closing Control...
[2023-12-13 07:20:09,155: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2023-12-13 07:20:09,155: DEBUG/MainProcess] | Consumer: Closing event loop...
[2023-12-13 07:20:09,155: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2023-12-13 07:20:09,155: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2023-12-13 07:20:09,157: DEBUG/MainProcess] | Consumer: Stopping Control...
[2023-12-13 07:20:09,157: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2023-12-13 07:20:09,157: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:20:09,157: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2023-12-13 07:20:09,157: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2023-12-13 07:20:09,158: DEBUG/MainProcess] | Consumer: Stopping Events...
[2023-12-13 07:20:09,158: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2023-12-13 07:20:09,158: DEBUG/MainProcess] | Worker: Terminating Pool...
[2023-12-13 07:20:09,158: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
[2023-12-13 07:20:09,660: DEBUG/MainProcess] | Worker: Terminating Hub...
[2023-12-13 07:20:09,660: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2023-12-13 07:20:09,660: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2023-12-13 07:20:09,660: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2023-12-13 07:20:09,660: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:20:09,660: DEBUG/MainProcess] Closing consumer channel...
[2023-12-13 07:20:09,660: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2023-12-13 07:20:09,660: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2023-12-13 07:20:09,661: DEBUG/MainProcess] | Consumer: Shutdown Connection...
[2023-12-13 07:20:23,297: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2023-12-13 07:20:23,298: DEBUG/MainProcess] | Worker: Building graph...
[2023-12-13 07:20:23,298: DEBUG/MainProcess] | Worker: New boot order: {StateDB, Beat, Timer, Hub, Pool, Autoscaler, Consumer}
[2023-12-13 07:20:23,301: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2023-12-13 07:20:23,301: DEBUG/MainProcess] | Consumer: Building graph...
[2023-12-13 07:20:23,306: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Tasks, Control, Heart, Agent, Gossip, event loop}
[2023-12-13 07:20:23,315: DEBUG/MainProcess] | Worker: Starting Hub
[2023-12-13 07:20:23,315: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:20:23,315: DEBUG/MainProcess] | Worker: Starting Pool
[2023-12-13 07:20:23,667: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:20:23,667: DEBUG/MainProcess] | Worker: Starting Consumer
[2023-12-13 07:20:23,667: DEBUG/MainProcess] | Consumer: Starting Connection
[2023-12-13 07:20:23,668: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:20:23,674: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-13 07:20:23,674: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:20:23,674: DEBUG/MainProcess] | Consumer: Starting Events
[2023-12-13 07:20:23,674: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:20:23,675: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:20:23,675: DEBUG/MainProcess] | Consumer: Starting Mingle
[2023-12-13 07:20:23,675: INFO/MainProcess] mingle: searching for neighbors
[2023-12-13 07:20:23,678: INFO/MainProcess] sync with celery@298636e574af
[2023-12-13 07:20:24,681: INFO/MainProcess] mingle: sync with 1 nodes
[2023-12-13 07:20:24,681: DEBUG/MainProcess] mingle: processing reply from celery@d2e1e9846bbd
[2023-12-13 07:20:24,681: INFO/MainProcess] mingle: sync complete
[2023-12-13 07:20:24,681: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:20:24,681: DEBUG/MainProcess] | Consumer: Starting Tasks
[2023-12-13 07:20:24,683: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:20:24,683: DEBUG/MainProcess] | Consumer: Starting Control
[2023-12-13 07:20:24,685: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:20:24,685: DEBUG/MainProcess] | Consumer: Starting Heart
[2023-12-13 07:20:24,686: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:20:24,686: DEBUG/MainProcess] | Consumer: Starting Gossip
[2023-12-13 07:20:24,688: DEBUG/MainProcess] ^-- substep ok
[2023-12-13 07:20:24,688: DEBUG/MainProcess] | Consumer: Starting event loop
[2023-12-13 07:20:24,688: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2023-12-13 07:20:24,689: INFO/MainProcess] celery@298636e574af ready.
[2023-12-13 07:20:24,689: DEBUG/MainProcess] basic.qos: prefetch_count->96
[2023-12-13 07:20:25,065: DEBUG/MainProcess] celery@d2e1e9846bbd joined the party
[2023-12-13 07:20:41,516: ERROR/MainProcess] Received unregistered task of type 'app.tasks.run_task'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
https://docs.celeryq.dev/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["/root/hip_storage/2d264628-db3f-44f2-a36a-f5174b726430.hiplc", "/obj/test", "dd0cd528-c459-4a55-b024-66264bddbe08.png"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (196b)

The full contents of the message headers:
{'lang': 'py', 'task': 'app.tasks.run_task', 'id': '75f01676-0f18-4964-bb47-079c6a2b16b3', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '75f01676-0f18-4964-bb47-079c6a2b16b3', 'parent_id': None, 'argsrepr': "('/root/hip_storage/2d264628-db3f-44f2-a36a-f5174b726430.hiplc', '/obj/test', 'dd0cd528-c459-4a55-b024-66264bddbe08.png')", 'kwargsrepr': '{}', 'origin': 'gen1711@298636e574af', 'ignore_result': False, 'replaced_task_nesting': 0, 'stamped_headers': None, 'stamps': {}}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 658, in on_task_received
    strategy = strategies[type_]
KeyError: 'app.tasks.run_task'
[2023-12-13 07:29:01,130: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 742, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.9/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 1343, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 568, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 912, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 922, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 824, in parse_response
    response = self._execute(conn, try_read)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 800, in _execute
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 802, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 789, in _disconnect_raise_connect
    raise error
  File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 801, in <lambda>
    lambda: command(*args, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 822, in try_read
    return conn.read_response(disconnect_on_error=False, push_request=True)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 500, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.9/site-packages/redis/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.9/site-packages/redis/_parsers/resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.9/site-packages/redis/_parsers/socket.py", line 115, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.9/site-packages/redis/_parsers/socket.py", line 68, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2023-12-13 07:29:01,132: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:391: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered
back to the queue. You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss
setting. In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2023-12-13 07:29:01,133: DEBUG/MainProcess] | Consumer: Restarting event loop...
[2023-12-13 07:29:01,133: DEBUG/MainProcess] | Consumer: Restarting Gossip...
[2023-12-13 07:29:01,133: DEBUG/MainProcess] | Consumer: Restarting Heart...
[2023-12-13 07:29:01,134: DEBUG/MainProcess] | Consumer: Restarting Control...
[2023-12-13 07:29:01,134: DEBUG/MainProcess] | Consumer: Restarting Tasks...
[2023-12-13 07:29:01,134: DEBUG/MainProcess] Canceling task consumer...
[2023-12-13 07:29:01,135: DEBUG/MainProcess] | Consumer: Restarting Mingle...
[2023-12-13 07:29:01,135: DEBUG/MainProcess] | Consumer: Restarting Events...
[2023-12-13 07:29:01,135: DEBUG/MainProcess] | Consumer: Restarting Connection...
[2023-12-13 07:29:01,135: DEBUG/MainProcess] | Consumer: Starting Connection
[2023-12-13 07:29:01,135: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-13 07:29:01,136: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2023-12-13 07:29:07,096: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -2 connecting to redis:6379. Name or service not known..
Trying again in 4.00 seconds... (2/100)

[2023-12-14 04:39:07,278: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-14 04:39:07,284: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-14 04:39:07,284: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-14 04:39:07,287: INFO/MainProcess] mingle: searching for neighbors
[2023-12-14 04:39:08,291: INFO/MainProcess] mingle: all alone
[2023-12-14 04:39:08,299: INFO/MainProcess] celery@edd16634e5c4 ready.
[2023-12-14 04:39:08,300: INFO/MainProcess] Task app.tasks.run_task[0c84137f-d4a1-4c90-8e43-15df5289a57e] received
[2023-12-14 04:39:08,315: INFO/ForkPoolWorker-14] Task app.tasks.run_task[0c84137f-d4a1-4c90-8e43-15df5289a57e] succeeded in 0.013999185000102443s: None
[2023-12-14 07:42:02,745: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-14 07:42:02,750: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-14 07:42:02,751: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-14 07:42:02,752: INFO/MainProcess] mingle: searching for neighbors
[2023-12-14 07:42:03,756: INFO/MainProcess] mingle: all alone
[2023-12-14 07:42:03,764: INFO/MainProcess] celery@9df49e444b4f ready.
[2023-12-14 07:42:35,542: INFO/MainProcess] Task app.tasks.run_task[b45105d5-a75b-4781-9cc6-048d07e422a5] received
[2023-12-14 07:42:35,560: INFO/ForkPoolWorker-14] Task app.tasks.run_task[b45105d5-a75b-4781-9cc6-048d07e422a5] succeeded in 0.01635207800063654s: None
[2023-12-14 07:45:16,115: INFO/MainProcess] Task app.tasks.run_task[c4f311db-43de-4598-b5c5-ecf3fb812cd2] received
[2023-12-14 07:45:16,132: INFO/ForkPoolWorker-14] Task app.tasks.run_task[c4f311db-43de-4598-b5c5-ecf3fb812cd2] succeeded in 0.015508734999457374s: None
[2023-12-14 07:45:50,153: INFO/MainProcess] Task app.tasks.run_task[b75dd45b-ee40-4e15-bbbf-d083280ed064] received
[2023-12-14 07:45:50,168: INFO/ForkPoolWorker-14] Task app.tasks.run_task[b75dd45b-ee40-4e15-bbbf-d083280ed064] succeeded in 0.01431818499986548s: None
[2023-12-14 07:51:12,629: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-14 07:51:12,636: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-14 07:51:12,636: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-14 07:51:12,638: INFO/MainProcess] mingle: searching for neighbors
[2023-12-14 07:51:13,643: INFO/MainProcess] mingle: all alone
[2023-12-14 07:51:13,650: INFO/MainProcess] celery@383c53173c54 ready.
[2023-12-14 07:51:59,196: INFO/MainProcess] Task app.tasks.run_task[196abbb2-c2be-4017-b0dc-aeb5574d0f94] received
[2023-12-14 07:51:59,214: INFO/ForkPoolWorker-14] Task app.tasks.run_task[196abbb2-c2be-4017-b0dc-aeb5574d0f94] succeeded in 0.016191560000152094s: None
[2023-12-17 02:52:54,286: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-17 02:52:54,314: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-17 02:52:54,315: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-17 02:52:54,317: INFO/MainProcess] mingle: searching for neighbors
[2023-12-17 02:52:55,328: INFO/MainProcess] mingle: all alone
[2023-12-17 02:52:55,338: INFO/MainProcess] celery@c35634a01402 ready.
[2023-12-17 05:17:26,891: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-17 05:17:26,971: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-17 05:17:26,974: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-17 05:17:26,979: INFO/MainProcess] mingle: searching for neighbors
[2023-12-17 05:17:28,006: INFO/MainProcess] mingle: all alone
[2023-12-17 05:17:28,032: INFO/MainProcess] celery@615469cff224 ready.
[2023-12-17 05:17:28,050: INFO/MainProcess] Task app.tasks.run_task[262ef1a7-368c-4891-8cdc-103c7ebf513e] received
[2023-12-17 05:17:28,060: INFO/MainProcess] Task app.tasks.run_task[c2026079-0ca2-4919-9736-a74cf9703543] received
[2023-12-17 05:17:28,064: INFO/MainProcess] Task app.tasks.run_task[e69626a9-1ee1-463f-b5b6-7b71f5441e2e] received
[2023-12-17 05:17:28,066: INFO/MainProcess] Task app.tasks.run_task[d2fad7eb-609c-4d5e-9739-6834504fb0d5] received
[2023-12-17 05:17:28,119: INFO/ForkPoolWorker-8] Task app.tasks.run_task[d2fad7eb-609c-4d5e-9739-6834504fb0d5] succeeded in 0.051303961998200975s: None
[2023-12-17 05:17:28,125: INFO/ForkPoolWorker-6] Task app.tasks.run_task[262ef1a7-368c-4891-8cdc-103c7ebf513e] succeeded in 0.0680770239996491s: None
[2023-12-17 05:17:28,156: INFO/ForkPoolWorker-12] Task app.tasks.run_task[c2026079-0ca2-4919-9736-a74cf9703543] succeeded in 0.07183732600242365s: None
[2023-12-17 05:17:28,155: INFO/ForkPoolWorker-7] Task app.tasks.run_task[e69626a9-1ee1-463f-b5b6-7b71f5441e2e] succeeded in 0.07222379200538853s: None
[2023-12-17 05:25:03,824: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-17 05:25:03,839: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-17 05:25:03,839: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-17 05:25:03,843: INFO/MainProcess] mingle: searching for neighbors
[2023-12-17 05:25:04,851: INFO/MainProcess] mingle: all alone
[2023-12-17 05:25:04,864: INFO/MainProcess] celery@bd7ceb9f9b6a ready.
[2023-12-17 05:27:42,078: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-17 05:27:42,094: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-17 05:27:42,094: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-17 05:27:42,096: INFO/MainProcess] mingle: searching for neighbors
[2023-12-17 05:27:43,106: INFO/MainProcess] mingle: all alone
[2023-12-17 05:27:43,121: INFO/MainProcess] celery@2cc6ce7b603a ready.
[2023-12-17 05:28:17,300: INFO/MainProcess] Task app.tasks.run_task[6a20a6af-161a-4f8f-b48e-1ac1b6980d27] received
[2023-12-17 05:28:17,347: INFO/ForkPoolWorker-6] Task app.tasks.run_task[6a20a6af-161a-4f8f-b48e-1ac1b6980d27] succeeded in 0.03937488700466929s: None
[2023-12-17 05:36:00,516: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-17 05:36:00,534: INFO/MainProcess] Connected to redis://redis:6379/0
[2023-12-17 05:36:00,534: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-12-17 05:36:00,536: INFO/MainProcess] mingle: searching for neighbors
[2023-12-17 05:36:01,546: INFO/MainProcess] mingle: all alone
[2023-12-17 05:36:01,573: INFO/MainProcess] celery@c9272dedf383 ready.
[2023-12-17 05:36:23,555: INFO/MainProcess] Task app.tasks.run_task[14f4b3f5-4b72-4782-9baa-877b70fb4c8f] received
[2023-12-17 05:36:23,595: INFO/ForkPoolWorker-5] Task app.tasks.run_task[14f4b3f5-4b72-4782-9baa-877b70fb4c8f] succeeded in 0.032950183005596045s: None
